version: "2"
services:
  db:
    image: "postgres"
    container_name: "my_postgres_tov"
    environment:
      - POSTGRES_USER=rt
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=tov
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      
  gateway:
    image: nginx
    network_mode: "host"
    volumes:
      - ./gateway.nginx:/etc/nginx/conf.d/default.conf
